/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Validator, ValidatorEntry, } from "./validators";
export namespace Components {
    interface AnimatedInput {
        "validate": () => Promise<void>;
        "validator": Array<string | ValidatorEntry | Validator<string>>;
        "value": string;
    }
    interface MyComponent {
        "validator": Array<string | ValidatorEntry | Validator<string>>;
        "value": string;
    }
}
declare global {
    interface HTMLAnimatedInputElement extends Components.AnimatedInput, HTMLStencilElement {
    }
    var HTMLAnimatedInputElement: {
        prototype: HTMLAnimatedInputElement;
        new (): HTMLAnimatedInputElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "animated-input": HTMLAnimatedInputElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AnimatedInput {
        "onChanged"?: (event: CustomEvent<string>) => void;
        "validator"?: Array<string | ValidatorEntry | Validator<string>>;
        "value"?: string;
    }
    interface MyComponent {
        "onChanged"?: (event: CustomEvent<string>) => void;
        "validator"?: Array<string | ValidatorEntry | Validator<string>>;
        "value"?: string;
    }
    interface IntrinsicElements {
        "animated-input": AnimatedInput;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "animated-input": LocalJSX.AnimatedInput & JSXBase.HTMLAttributes<HTMLAnimatedInputElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
